version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    depends_on:
      - php
      - mysql
    ports:
      - "8080:80"
    volumes:
      - ../hapoLearn:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    image: sonhv/php-hapo:v1.0
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ../hapoLearn:/var/www/html
    ports:
      - "9000:9000"
    links:
      - mysql
  mysql:
    image: mysql:8.0.32
    restart: unless-stopped
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "hapo_db"